### ISSUE TITLE
Gmail password in your repo

### ISSUE THREAD

**Issue by marcaurele** [QuentinRiv/KeyLog#1]
This line does not look safe:
https://github.com/QuentinRiv/KeyLog/blob/883cf215b71901405004cb74946ac0d79a66455b/Keylogger.py#L63

You should change your password immediately and remove it from the git history of the project.

**Comment by QuentinRiv** [comment]
Indeed, that's a rookie mistake...
But now I understand why I had a security alarm ;)

**Comment by marcaurele** [comment]
It's still in the history of your repo ;)
